spring.application.name=auth-service
server.port=${PORT:8081}

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/utkarsh}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:mysql}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey123456}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=https://auth-service-production-815b.up.railway.app/login/oauth2/code/google

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

