spring.application.name=api-gateway
server.port=${PORT:8090}

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey123456}

# Enable Discovery
spring.cloud.gateway.discovery.locator.enabled=false

# AUTH SERVICE ROUTE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# QMA SERVICE ROUTE
spring.cloud.gateway.routes[1].id=qma-service
spring.cloud.gateway.routes[1].uri=${QMA_SERVICE_URL:http://localhost:8080}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**

#CORS

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=false
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

