spring.application.name=eureka-server
server.port=${PORT:8761}

eureka.instance.hostname=${HOSTNAME:localhost}
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.server.enable-self-preservation=false